version: '3.8'
services:
  chop-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chop
    restart: unless-stopped
    networks:
      - web
networks:
  web:
    external: true